#!/usr/bin/env python3
"""Extracts the bitmap fonts and icons from the Rust firmware into C++ tables.

The C++ firmware draws with exactly the same glyphs and icons as the Rust
firmware; this script is the single conversion step. Run it from the
repository root after changing rust-firmware/src/{font8x16,font5x7,icons}.rs.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "rust-firmware" / "src"
OUT = ROOT / "firmware" / "main" / "assets"


def numbers(text):
    return [int(n, 0) for n in re.findall(r"0x[0-9a-fA-F]+|\b\d+\b", text)]


def block(source, name):
    match = re.search(rf"{name}\s*:[^=]*=\s*\[(.*?)\];", source, re.S)
    if not match:
        raise SystemExit(f"{name} not found")
    return match.group(1)


def font8x16():
    src = (SRC / "font8x16.rs").read_text()
    widths = numbers(block(src, "GLYPH_WIDTHS"))
    glyphs = numbers(block(src, "GLYPHS"))
    assert len(glyphs) == len(widths) * 16, (len(glyphs), len(widths))
    lines = ["// Generated by firmware/tools/gen_assets.py from rust-firmware/src/font8x16.rs.",
             "#pragma once", "#include <cstdint>", "",
             "namespace assets {", "",
             "constexpr int kFont16Height = 16;",
             "constexpr uint32_t kFont16First = 0x20;",
             f"constexpr uint32_t kFont16Last = 0x{0x20 + len(widths) - 1:02X};", "",
             f"constexpr uint8_t kFont16Widths[{len(widths)}] = {{"]
    for i in range(0, len(widths), 16):
        lines.append("    " + ", ".join(str(w) for w in widths[i:i + 16]) + ",")
    lines += ["};", "", "// One row per uint16_t, MSB is the leftmost column.",
              f"constexpr uint16_t kFont16Glyphs[{len(widths)}][16] = {{"]
    for i in range(len(widths)):
        row = glyphs[i * 16:(i + 1) * 16]
        lines.append("    {" + ", ".join(f"0x{v:04x}" for v in row) + "},")
    lines += ["};", "", "}  // namespace assets", ""]
    (OUT / "font8x16.h").write_text("\n".join(lines))


def icons():
    src = (SRC / "icons.rs").read_text()
    found = re.findall(r"pub const (\w+): Icon = Icon \{\s*width: (\d+),\s*rows: &\[(.*?)\],\s*\};", src, re.S)
    lines = ["// Generated by firmware/tools/gen_assets.py from rust-firmware/src/icons.rs.",
             "#pragma once", "#include <cstdint>", "",
             "namespace assets {", "",
             "struct Icon {", "    uint8_t width;", "    uint8_t height;",
             "    const uint32_t* rows;  // MSB is the leftmost column", "};", ""]
    for name, width, rows in found:
        values = numbers(rows)
        lines.append(f"constexpr uint32_t k{name.title().replace('_', '')}Rows[] = {{")
        for i in range(0, len(values), 7):
            lines.append("    " + ", ".join(f"0x{v:08x}" for v in values[i:i + 7]) + ",")
        lines.append("};")
        cname = name.title().replace('_', '')
        lines.append(f"constexpr Icon k{cname}{{{width}, {len(values)}, k{cname}Rows}};")
        lines.append("")
    lines += ["}  // namespace assets", ""]
    (OUT / "icons.h").write_text("\n".join(lines))
    return [n for n, _, _ in found]


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    font8x16()
    print("icons:", ", ".join(icons()))
